package gui;

import dao.MaterijalDAO;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FilenameFilter;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.xml.ws.Endpoint;
import modeli.Materijal;
import org.eclipse.persistence.tools.file.FileUtil;
import servisi.MaterijalServis;
import utils.Konverter;

/**
 *
 * @author zi
 */

public class MainForm extends javax.swing.JFrame {
	
	private MaterijalDAO materijalDAO;
	private List<Materijal> materijali;
	private DefaultTableModel modelMaterijali;
	
	/**
	 * Creates new form MainForm
	 */
	public MainForm() {
		materijalDAO = new MaterijalDAO();
		initModels();
		initComponents();
		osvezi();
	}
	
	private void osvezi() {
		int razred = (int)spinnerRazred.getValue();
		int lekcija = (int)spinnerLekcija.getValue();
		
		materijali = materijalDAO.preuzmi(razred, lekcija);
		
		while(modelMaterijali.getRowCount() > 0) {
			modelMaterijali.removeRow(0);
		}
		
		for(Materijal materijal : materijali) {
			modelMaterijali.addRow(new Object[] {
				materijal.getId(),
				materijal.getRazred(),
				materijal.getLekcija()
			});
		}
		
		lblSlika.setIcon(new ImageIcon());
	}
	
	private void initModels() {
		modelMaterijali = new DefaultTableModel(
			new Object[][] {},
			new String[] {
				"ИД",
				"Разред",
				"Лекција"
			}
		) {
			@Override
			public boolean isCellEditable(int i, int i1) {
				return false;
			}
			
		};
	}
	
	public void prikaziSliku(Materijal materijal) {
		lblSlika.setIcon(new ImageIcon());
		try {
			materijal.ucitajSliku();
			BufferedImage slika = Konverter.byteArrayToImage(materijal.getSlika());
			Image sSlika = slika.getScaledInstance(lblSlika.getWidth(), lblSlika.getHeight(), Image.SCALE_SMOOTH);
			lblSlika.setIcon(new ImageIcon(sSlika));
		} catch (IOException ex) {
			ex.printStackTrace();
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpGlavni = new javax.swing.JTabbedPane();
        panelServis = new javax.swing.JPanel();
        btnPokreni = new javax.swing.JButton();
        panelMaterijali = new javax.swing.JPanel();
        lblRazred = new javax.swing.JLabel();
        spinnerRazred = new javax.swing.JSpinner();
        lblLekcija = new javax.swing.JLabel();
        spinnerLekcija = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMaterijali = new javax.swing.JTable();
        lblSlika = new javax.swing.JLabel();
        btnNoviRed = new javax.swing.JButton();
        btnUcitajSliku = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ЧАС");

        btnPokreni.setText("ПОКРЕНИ");
        btnPokreni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPokreniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelServisLayout = new javax.swing.GroupLayout(panelServis);
        panelServis.setLayout(panelServisLayout);
        panelServisLayout.setHorizontalGroup(
            panelServisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelServisLayout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(btnPokreni)
                .addContainerGap(274, Short.MAX_VALUE))
        );
        panelServisLayout.setVerticalGroup(
            panelServisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelServisLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(btnPokreni)
                .addContainerGap(337, Short.MAX_VALUE))
        );

        tpGlavni.addTab("Сервис", panelServis);

        lblRazred.setText("Разред:");

        spinnerRazred.setModel(new javax.swing.SpinnerNumberModel(5, 5, 8, 1));
        spinnerRazred.setToolTipText("");
        spinnerRazred.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerRazredStateChanged(evt);
            }
        });

        lblLekcija.setText("Лекција:");

        spinnerLekcija.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99, 1));
        spinnerLekcija.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerLekcijaStateChanged(evt);
            }
        });

        tblMaterijali.setModel(modelMaterijali);
        tblMaterijali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblMaterijaliMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblMaterijali);

        lblSlika.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSlikaMouseClicked(evt);
            }
        });

        btnNoviRed.setText("Додај");
        btnNoviRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoviRedActionPerformed(evt);
            }
        });

        btnUcitajSliku.setText("Учитај слику ...");
        btnUcitajSliku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUcitajSlikuActionPerformed(evt);
            }
        });

        btnObrisi.setText("Обриши");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMaterijaliLayout = new javax.swing.GroupLayout(panelMaterijali);
        panelMaterijali.setLayout(panelMaterijaliLayout);
        panelMaterijaliLayout.setHorizontalGroup(
            panelMaterijaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMaterijaliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMaterijaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMaterijaliLayout.createSequentialGroup()
                        .addComponent(lblRazred)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinnerRazred, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblLekcija)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinnerLekcija, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelMaterijaliLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelMaterijaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSlika, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelMaterijaliLayout.createSequentialGroup()
                                .addGroup(panelMaterijaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnUcitajSliku)
                                    .addGroup(panelMaterijaliLayout.createSequentialGroup()
                                        .addComponent(btnNoviRed)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnObrisi)))
                                .addGap(0, 48, Short.MAX_VALUE))))))
        );
        panelMaterijaliLayout.setVerticalGroup(
            panelMaterijaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMaterijaliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMaterijaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRazred)
                    .addComponent(spinnerRazred, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLekcija)
                    .addComponent(spinnerLekcija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMaterijaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                    .addGroup(panelMaterijaliLayout.createSequentialGroup()
                        .addComponent(lblSlika, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUcitajSliku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelMaterijaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNoviRed)
                            .addComponent(btnObrisi))))
                .addContainerGap())
        );

        tpGlavni.addTab("Материјали за час", panelMaterijali);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpGlavni)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpGlavni)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spinnerRazredStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerRazredStateChanged
        osvezi();
    }//GEN-LAST:event_spinnerRazredStateChanged

    private void spinnerLekcijaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerLekcijaStateChanged
        osvezi();
    }//GEN-LAST:event_spinnerLekcijaStateChanged

    private void btnNoviRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoviRedActionPerformed
        Materijal materijal = new Materijal();
		materijal.setRazred((int)spinnerRazred.getValue());
		materijal.setLekcija((int)spinnerLekcija.getValue());
		materijalDAO.dodaj(materijal);
		osvezi();
    }//GEN-LAST:event_btnNoviRedActionPerformed

    private void tblMaterijaliMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMaterijaliMousePressed
        int row = tblMaterijali.rowAtPoint(evt.getPoint());
		Materijal materijal = materijali.get(row);
		prikaziSliku(materijal);
    }//GEN-LAST:event_tblMaterijaliMousePressed

    private void lblSlikaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSlikaMouseClicked
        JFrame frmSlika = new JFrame();
		int row = tblMaterijali.getSelectedRow();
		Materijal materijal = materijali.get(row);
		
		frmSlika.setTitle(String.valueOf(materijal.getId()));
		try {
			BufferedImage slika = Konverter.byteArrayToImage(materijal.getSlika());
			frmSlika.add(new JLabel(new ImageIcon(slika)));
			frmSlika.setVisible(true);
			frmSlika.pack();
		} catch (IOException ex) {
			ex.printStackTrace();
		}
    }//GEN-LAST:event_lblSlikaMouseClicked

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        int row = tblMaterijali.getSelectedRow();
		if(row >= 0) {
			Materijal materijal = materijali.get(row);
			materijalDAO.obrisi(materijal);
			osvezi();
		}
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnPokreniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPokreniActionPerformed
        new Thread(new Runnable() {
			@Override
			public void run() {
				Endpoint.publish("http://0.0.0.0:5001/Cas", new MaterijalServis());
			}
		}).start();
    }//GEN-LAST:event_btnPokreniActionPerformed

    private void btnUcitajSlikuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUcitajSlikuActionPerformed
        int row = tblMaterijali.getSelectedRow();
		if(row < 0)
			return;
		Materijal materijal = materijali.get(row);
		
		JFileChooser fileChooser = new JFileChooser();
		fileChooser.setFileFilter(new FileNameExtensionFilter("Slika", "jpg"));
		if(fileChooser.showOpenDialog(MainForm.this) == JFileChooser.APPROVE_OPTION) {
			try {
				File inFile = fileChooser.getSelectedFile();
				File outFile = new File("res/materijal/" + materijal.getId() + ".jpg");
				outFile.delete();
				outFile.createNewFile();
				FileUtil.copy(new FileInputStream(inFile), new FileOutputStream(outFile));
				prikaziSliku(materijal);
			} catch (Exception ex) {
				ex.printStackTrace();
			}
		}
    }//GEN-LAST:event_btnUcitajSlikuActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			com.jtattoo.plaf.mint.MintLookAndFeel.setTheme("Mint");
			UIManager.setLookAndFeel("com.jtattoo.plaf.mint.MintLookAndFeel");
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainForm().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNoviRed;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPokreni;
    private javax.swing.JButton btnUcitajSliku;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLekcija;
    private javax.swing.JLabel lblRazred;
    private javax.swing.JLabel lblSlika;
    private javax.swing.JPanel panelMaterijali;
    private javax.swing.JPanel panelServis;
    private javax.swing.JSpinner spinnerLekcija;
    private javax.swing.JSpinner spinnerRazred;
    private javax.swing.JTable tblMaterijali;
    private javax.swing.JTabbedPane tpGlavni;
    // End of variables declaration//GEN-END:variables
}
