package gui;

import dao.PitanjeDAO;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import modeli.Pitanje;
import org.eclipse.persistence.tools.file.FileUtil;

/**
 *
 * @author zi
 */

public class NovoPitanjeDialog extends javax.swing.JDialog {
	
	private File slika = null;
	private PitanjeDAO pitanjeDAO;
	private int kvizId;
	
	/**
	 * Creates new form NovoPitanjeDialog
	 */
	public NovoPitanjeDialog(java.awt.Frame parent, boolean modal, int kvizId) {
		super(parent, modal);
		this.kvizId = kvizId;
		pitanjeDAO = new PitanjeDAO();
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTacanOdgovor = new javax.swing.JLabel();
        cbTacanOdgovor = new javax.swing.JComboBox<>();
        btnSnimi = new javax.swing.JButton();
        btnOtkazi = new javax.swing.JButton();
        lblSlikaNatpis = new javax.swing.JLabel();
        lblSlika = new javax.swing.JLabel();
        btnUcitajSliku = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ново питање");

        lblTacanOdgovor.setText("Тачан одговор:");

        cbTacanOdgovor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "А", "Б", "Ц", "Д" }));

        btnSnimi.setText("Сними");
        btnSnimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSnimiActionPerformed(evt);
            }
        });

        btnOtkazi.setText("Откажи");
        btnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziActionPerformed(evt);
            }
        });

        lblSlikaNatpis.setText("Слика:");

        btnUcitajSliku.setText("Учитај слику ...");
        btnUcitajSliku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUcitajSlikuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSlikaNatpis)
                            .addComponent(lblTacanOdgovor)
                            .addComponent(btnUcitajSliku))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbTacanOdgovor, 0, 207, Short.MAX_VALUE)
                            .addComponent(lblSlika, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSnimi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOtkazi)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTacanOdgovor)
                    .addComponent(cbTacanOdgovor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSlika, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSlikaNatpis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUcitajSliku)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOtkazi)
                    .addComponent(btnSnimi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
        dispose();
    }//GEN-LAST:event_btnOtkaziActionPerformed

    private void btnUcitajSlikuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUcitajSlikuActionPerformed
        JFileChooser fileChooser = new JFileChooser();
		fileChooser.setFileFilter(new FileNameExtensionFilter("Slika", "jpg"));
		if(fileChooser.showSaveDialog(NovoPitanjeDialog.this) == JFileChooser.APPROVE_OPTION) {
			try {
				slika = fileChooser.getSelectedFile();
				BufferedImage biSlika = ImageIO.read(slika);
				Image sSlika = biSlika.getScaledInstance(lblSlika.getWidth(), lblSlika.getHeight(), Image.SCALE_SMOOTH);
				lblSlika.setIcon(new ImageIcon(sSlika));
			} catch(Exception ex) {
				ex.printStackTrace();
			}
		}
    }//GEN-LAST:event_btnUcitajSlikuActionPerformed

    private void btnSnimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSnimiActionPerformed
        Pitanje pitanje = new Pitanje();
		pitanje.setIdKviz(kvizId);
		pitanje.setTacanOdgovor(cbTacanOdgovor.getSelectedIndex() + 1);
		if(!pitanjeDAO.dodaj(pitanje)) {
			JOptionPane.showMessageDialog(null, "Грешка приликом креирања питања");
			return;
		}
		
		if(slika != null) {
			try {
				File outFile = new File("res/kviz/" + pitanje.getId() + ".jpg");
				outFile.delete();
				outFile.createNewFile();
				FileUtil.copy(new FileInputStream(slika), new FileOutputStream(outFile));
			} catch (Exception ex) {
				ex.printStackTrace();
			}
		}
		
		((MainForm)getParent()).osveziKvizove();
		dispose();
    }//GEN-LAST:event_btnSnimiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JButton btnSnimi;
    private javax.swing.JButton btnUcitajSliku;
    private javax.swing.JComboBox<String> cbTacanOdgovor;
    private javax.swing.JLabel lblSlika;
    private javax.swing.JLabel lblSlikaNatpis;
    private javax.swing.JLabel lblTacanOdgovor;
    // End of variables declaration//GEN-END:variables
}
